version: 1.0.{build}
image: Visual Studio 2019

before_build:
  - if exist _build rmdir /s /q _build
  - if exist CMakeCache.txt del CMakeCache.txt

build_script:
  - mkdir _build
  - cd _build
  - cmake ..
  - cmake --build . --config Release

test_script:
  - ctest -C Release --output-on-failure

artifacts:
  - path: _build\Release\*.exe
    name: lab04
