language: cpp
dist: focal

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9
    
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-focal-13
          packages:
            - clang-13
      env:
        - CXX=clang++-13
        - CC=clang-13

before_script:
  # Очищаем от старых файлов кэша
  - rm -rf _build CMakeCache.txt CMakeFiles/

script:
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build .
  - cmake --build . --target install
